use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn to_pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if upper {
                out.push(ch.to_ascii_uppercase());
                upper = false;
            } else {
                out.push(ch.to_ascii_lowercase());
            }
        } else {
            upper = true;
        }
    }
    if out.is_empty() {
        "Component".to_string()
    } else {
        out
    }
}

fn extract_attr_values(contents: &str, tag: &str, attr: &str) -> Vec<String> {
    // Extremely small HTML-ish extractor for build-time codegen.
    // Finds occurrences like: `<tag ... attr="VALUE" ...>`
    let mut out = Vec::new();
    let contents_lc = contents.to_ascii_lowercase();
    let tag_lc = tag.to_ascii_lowercase();
    let attr_lc = attr.to_ascii_lowercase();

    let mut i = 0usize;
    while let Some(pos) = contents_lc[i..].find(&format!("<{}", tag_lc)) {
        let start = i + pos;
        let Some(gt_rel) = contents_lc[start..].find('>') else { break };
        let end = start + gt_rel;
        let chunk = &contents[start..=end];
        let chunk_lc = &contents_lc[start..=end];

        if let Some(a_pos) = chunk_lc.find(&format!("{}=", attr_lc)) {
            let after = a_pos + attr_lc.len() + 1;
            let rest = &chunk[after..];
            let rest_lc = &chunk_lc[after..];
            if rest_lc.starts_with('"') || rest_lc.starts_with('\'') {
                let q = rest.chars().next().unwrap();
                let rest2 = &rest[q.len_utf8()..];
                if let Some(q_end) = rest2.find(q) {
                    out.push(rest2[..q_end].to_string());
                }
            } else {
                // unquoted
                let mut end_idx = rest.len();
                for (idx, ch) in rest.char_indices() {
                    if ch.is_whitespace() || ch == '>' || ch == '/' {
                        end_idx = idx;
                        break;
                    }
                }
                out.push(rest[..end_idx].to_string());
            }
        }

        i = end + 1;
    }

    out.sort();
    out.dedup();
    out
}

fn has_children_slot(contents: &str) -> bool {
    let lc = contents.to_ascii_lowercase();
    lc.contains("<children") || lc.contains("<slot")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let components_dir = manifest_dir.join("resources").join("components");
    println!("cargo:rerun-if-changed={}", components_dir.display());

    let mut entries: Vec<PathBuf> = match fs::read_dir(&components_dir) {
        Ok(rd) => rd.filter_map(|e| e.ok().map(|e| e.path())).collect(),
        Err(_) => Vec::new(),
    };
    entries.retain(|p| p.extension().and_then(|s| s.to_str()) == Some("html"));
    entries.sort();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("viewkit_builtin_components.rs");
    let mut out = String::new();

    out.push_str("// @generated by build.rs. Do not edit.\n");
    out.push_str("use crate::ui::{ComponentBuilder, UIElement};\n\n");

    // Component types + constructors
    for path in &entries {
        let file_name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("component");
        let component_name = stem.to_string();
        let struct_name = format!("{}Component", to_pascal_case(stem));
        let contents = fs::read_to_string(path).unwrap_or_default();
        let mut all_types = extract_attr_values(&contents, "content", "type");
        all_types.sort();
        all_types.dedup();
        let has_children = has_children_slot(&contents);

        // Ensure build reruns when any file changes.
        println!("cargo:rerun-if-changed={}", path.display());

        out.push_str(&format!(
            "pub const VIEWKIT_COMPONENT_{}_TEMPLATE: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/resources/components/{}\"));\n",
            component_name.to_ascii_uppercase(),
            file_name
        ));

        out.push_str(&format!(
            "#[derive(Clone, Debug)]\npub struct {} {{ inner: ComponentBuilder }}\n",
            struct_name
        ));
        out.push_str(&format!("impl {} {{\n", struct_name));
        out.push_str(&format!(
            "  pub fn new() -> Self {{ Self {{ inner: ComponentBuilder::new(\"{}\") }} }}\n",
            component_name
        ));
        out.push_str(
            "  pub fn attr<K, V>(mut self, key: K, value: V) -> Self\n  where K: Into<String>, V: Into<serde_json::Value> {\n    self.inner = self.inner.attr(key, value);\n    self\n  }\n",
        );
        if has_children {
            out.push_str(
                "  pub fn children<I, E>(mut self, elems: I) -> Self\n  where I: IntoIterator<Item = E>, E: Into<UIElement> {\n    self.inner = self.inner.children(elems);\n    self\n  }\n",
            );
        }
        if all_types.iter().any(|t| t.eq_ignore_ascii_case("string")) {
            out.push_str(
                "  pub fn label<T: Into<String>>(mut self, value: T) -> Self {\n    self.inner = self.inner.content_typed(\"String\", value);\n    self\n  }\n",
            );
            out.push_str(
                "  pub fn text<T: Into<String>>(mut self, value: T) -> Self {\n    self.label(value)\n  }\n",
            );
        }
        if all_types.iter().any(|t| t.eq_ignore_ascii_case("image")) {
            out.push_str(
                "  pub fn image<T: Into<String>>(mut self, value: T) -> Self {\n    self.inner = self.inner.content_typed(\"Image\", value);\n    self\n  }\n",
            );
        }
        out.push_str("  pub fn into_elem(self) -> UIElement { self.inner.into_elem() }\n");
        out.push_str("}\n\n");
        out.push_str(&format!(
            "pub fn {}() -> {} {{ {}::new() }}\n\n",
            component_name, struct_name, struct_name
        ));
    }

    // Register function
    out.push_str("pub fn register_components<B: crate::backend::ComponentRenderer>(backend: &mut B) {\n");
    for path in &entries {
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("component");
        let component_name = stem.to_string();
        out.push_str(&format!(
            "  let _ = backend.register_component(\"{}\", VIEWKIT_COMPONENT_{}_TEMPLATE);\n",
            component_name,
            component_name.to_ascii_uppercase()
        ));
    }
    out.push_str("}\n");

    out.push_str("\n");
    out.push_str("pub fn template_for(name: &str) -> Option<&'static str> {\n  match name {\n");
    for path in &entries {
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("component");
        let component_name = stem.to_string();
        out.push_str(&format!(
            "    \"{}\" => Some(VIEWKIT_COMPONENT_{}_TEMPLATE),\n",
            component_name,
            component_name.to_ascii_uppercase()
        ));
    }
    out.push_str("    _ => None,\n  }\n}\n");

    let mut f = fs::File::create(&out_path).expect("create generated file");
    f.write_all(out.as_bytes())
        .expect("write generated file");
}
