name = "Example Window App"
bundle_id = "com.mochi.viewkit.example"
version = "0.1.0"
developer = "tas0dev"
entry = "entry.elf"
description = "GUI example application"
icon = "assets/icon.png"

resources = [
    "assets/icon.png"
]